# Generated by Django 4.2.6 on 2023-10-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_completed_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.major'),
        ),
    ]
