# Generated by Django 4.2.6 on 2023-10-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_minor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(to='products.cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='products.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.major'),
        ),
        migrations.AlterField(
            model_name='item',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.minor'),
        ),
    ]
